development: &default
  adapter: postgresql
  encoding: unicode
  database: clean-house-api_development
  pool: 5
  username: <%= ENV.fetch('DB_USERNAME', 'clean') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'clean') %>
  host: <%= ENV.fetch('DB_1_PORT_5432_TCP_ADDR', 'localhost') %>
  port: <%= ENV.fetch('DB_1_PORT_5432_TCP_PORT', '5432') %>

test: &test
  <<: *default
  database: clean-house-api_test

production:
  adapter: postgresql
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>
